#!/bin/bash
docker-compose down
docker-compose rm -f 
#docker-compose pull
#docker-compuse build --no-cache --force_recreate  --no-deps
#docker-compose up -d
docker-compose up --build  --force-recreate --no-deps   -d
#docker-compose up 
#docker-compose stop -t 1
