version: '2.3'
services:
        #postgres:
        #image: postgres:9.6
        #environment:
        #    - POSTGRES_USER=airflow
        #    - POSTGRES_PASSWORD=airflow
        #    - POSTGRES_DB=airflow
        #logging:
        #    options:
        #        max-size: 10m
        #        max-file: "3"
        #
    webserver:
        #user: ${CURRENT_UID}
        container_name: airflow
        #image: puckel/docker-airflow:1.10.9
        build: .
        #restart: always
        runtime: nvidia
        #depends_on:
        #    - postgres
        env_file:
                - tfx_metastore_mysql.env
        environment:
            - EXECUTOR=Local
            - AIRFLOW_DAG_DIR_LIST_INTERVAL=1 #dag_dir_list_interval
            - AIRFLOW_JOB_HEARTBEAT_SEC=5 # job_heartbeat_sec
            - AIRFLOW_SCHEDULER_HEARTBEAT_SEC=5 #job_heartbeat_sec
            - AIRFLOW_DAG_DEFAULT_VIEW=graph # job_heartbeat_sec
            - AIRFLOW_MAX_THREADS=1 # max_threads
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - NVIDIA_VISIBLE_DEVICES=all
            - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY} 
            #- LOAD_EX=y
        logging:
            options:
                max-size: 20m
                max-file: "3"
        volumes:
            - /home/mlops/mlops_dags:/usr/local/airflow/dags
            #- ./dags:/usr/local/airflow/dags
            - ./requirements.txt:/requirements.txt
            - ./config/webserver_config.py:/usr/local/airflow/webserver_config.py
            # - ./plugins:/usr/local/airflow/plugins

        ports:
            - "127.0.0.1:8081:8080"
            - "127.0.0.1:18888:18888"
            - "127.0.0.1:6006:6006"
        command: webserver
        #command: bash
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
